apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: smh
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: front
  sessionAffinity: None
  type: ClusterIP
