kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: front-v2-buildconfig
  namespace: testjin
spec:
  output:
    to:
      kind: DockerImage
      name: 'image-registry.openshift-image-registry.svc:5000/testjin/front:v2'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8'
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jaydenlee82/servicemesh-example.git'
    contextDir: /front_app_v2
  runPolicy: Serial
