apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: smh-front-gateway
  namespace: smh
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - front.apps.cluster3.mtp.local
    port:
      name: http
      number: 80
      protocol: HTTP
