apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: get-dr
  namespace: testjin
spec:
  host: get.testjin.svc.cluster.local 
  subsets:
  - labels:
      app: get
    name: v1
